### ISSUE TITLE
Several possible problems with Task 7

### ISSUE THREAD

**Issue by ingomueller-net** [root-project/opendata-benchmarks#3]
I have several doubts about Task 7.

First, there is no test about `Jet_pt > 30`.

Second, the signature of (`DelatR`](https://root.cern/doc/master/namespaceROOT_1_1VecOps.html#affb23cd678b4fbcf50e045aab12bd348) is `DeltaR(eta1, eta2, phi1, phi2), but it is used as `DeltaR(eta1, phi1, eta2, phi2)`.

Third, in the call to `DeltaR` should use `phi3` and `eta3`, not `phi2` and `eta2`. The benchmark says that jets are relevant where `pt > 10` *and* `dr < 0.4`.

Forth, I think this implementation has the same problem as the one based on groot. I have file an [issue](https://github.com/go-hep/examples/issues/4) there. I'll wait how the discussion goes there and report back with details afterwards.

**Comment by stwunsch** [comment]
Do you have a reference output for the last (fourth) issue raised or even a correct impl? Otherwise, I agree with the other three, these things should be fixed and adapted. On it!

**Comment by ingomueller-net** [comment]
Yes, @masonproffitt's implementation has [reference results](https://github.com/masonproffitt/opendata-benchmarks/tree/master/csv) for a tiny [sample of 1000 events](https://github.com/masonproffitt/opendata-benchmarks/tree/master/data). Our SQL and JSONiq implementations produce exactly the same results.

**Comment by masonproffitt** [comment]
Is the fourth issue mentioned here equivalent to saying that the condition `goodJet_antiMuon || goodJet_antiElectron` should be `goodJet_antiMuon && goodJet_antiElectron`? Because that's my issue with it (beyond the other three mentioned).

**Comment by ingomueller-net** [comment]
I haven't looked in detail but I think the problem is the behavior with zero muons (in which case, "there is no bad one" is true but "there is a good one" is not).

**Comment by masonproffitt** [comment]
That's not a problem here, though, right? In: https://github.com/root-project/opendata-benchmarks/blob/de5c3de5eb295d370b480de90dbb5089f6593b12/tasks/7/rdataframe_compiled.cxx#L9-L18 all jets will be accepted if there are no leptons with pt > 10 GeV.

But if there is either only an electron near the jet or only a muon a near the jet (not both), then the jet will still pass the `goodJet_antiMuon || goodJet_antiElectron` filter, hence the need to turn `||` into `&&`.

**Comment by stwunsch** [comment]
Fixed in the linked PR and also verified against the CSV linked above. Thanks @ingomueller-net @masonproffitt!
